### ISSUE TITLE
Feature roadmap

### ISSUE THREAD

**Issue by danielnachun** [cumc/pecotmr#36]
As our work on this package progress, this issue can help us enumerate possible future features of the package depending on the time and interests of contributors.  Some features will be needed for the manuscript submission, and others will make more sense to consider for future releases.

### Implemented
- [x] normal prior with SuSiE
- [x] `mr.ash` `normal_scale_mixture` prior with SuSiE
- [x] elastic net with `glmnet`
- [x] LASSO with `glmnet`
### To do (individual level)
- [ ] `mr.ash` priors
    - [ ] `horseshoe`
    - [ ] `point_normal`
    - [ ] `point_laplace`
- [ ] Rcpp wrapper for Dirichlet process regression ([manuscript](https://www.nature.com/articles/s41467-017-00470-2), [GitHub](https://github.com/biostatpzeng/DPR))
- [ ] Determine if the continuous shrinkage prior in PRS-cs ([manuscript](https://www.nature.com/articles/s41467-019-09718-5), [GitHub](https://github.com/getian107/PRScs)) can be extended from summary statistics to individual-level data, and implement in Rcpp.
### To do (summary statistics)
- [ ] normal prior with SuSiE
- [ ] all `mr.ash` priors
- [ ] `lassosum` for LASSO and elastic net ([manuscript](https://onlinelibrary.wiley.com/doi/abs/10.1002/gepi.22050), [GitHub](https://github.com/getian107/PRScs))
- [ ] Rcpp reimplementation of existing summary-based PRS-cs (see links above)
- [ ] Rcpp wrapper for summary-based Dirichlet process regression ([manuscript](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1009697), [GitHub](https://github.com/eldronzhou/SDPR))
### To do (other)
- [ ] Extension to genome-wide TWAS (this will be a separate manuscript) - see discussion about genome-wide extension for MR and polygenic risk scores.
## Mendelian randomization 
- [ ] Egger regression as an additional horizontal pleiotropy test to complement heterogeneity tests
- [ ] "Infinitesimal model" that incorporates all variants as instruments (this will be a separate manuscript, possibly in combination with the trans-QTL extension) - inspired by [OMR](https://academic.oup.com/bib/article/22/6/bbab322/6347949), and could exploit the fact that SuSiE gives us posterior effect sizes and standard errors, unlike most other fine mapping methods
    - [ ] How will this method handle weak instrument bias without removing variants - consider debiasing estimators like [dIVW](https://projecteuclid.org/journals/annals-of-statistics/volume-49/issue-4/Debiased-inverse-variance-weighted-estimator-in-two-sample-summary-data/10.1214/20-AOS2027.full) and [pIVW](https://onlinelibrary.wiley.com/doi/10.1111/biom.13732) - does OMR have this issue too?
    - [ ] Should show that SuSiE (especially with `mr.ash` priors) does a comparable job in terms of adjusting for LD as LD scores (used by OMR and [MRAID](https://www.science.org/doi/10.1126/sciadv.abl5744), and the variant selection methods used by [MR.LDP](https://academic.oup.com/nargab/article/2/2/lqaa028/5828855), [MR-Corr2](https://academic.oup.com/bioinformatics/article/38/2/303/6367765) and [MR-CUE](https://www.nature.com/articles/s41467-022-34164-1).
    - [ ] Are the heterogeneity tests and Egger regression still valid for testing for horizontal pleiotropy in the presence of so many weak instruments?
- [ ] Extension to genome-wide analysis with trans-QTLs (this will definitely be a separate manuscript):
    - [ ] Proper handling of correlated horizontal pleiotropy (CHP) is *critical*.  The most conservative existing approach is to just remove pleiotropic variants - other solutions are provided by [cause](https://www.nature.com/articles/s41588-020-0631-4), [MRAID](https://www.science.org/doi/10.1126/sciadv.abl5744), [MR-Corr2](https://academic.oup.com/bioinformatics/article/38/2/303/6367765), [MR-CUE](https://www.nature.com/articles/s41467-022-34164-1) and [MRcML](https://www.cell.com/ajhg/pdfExtended/S0002-9297(21)00219-6).  See also [this review](https://www.sciencedirect.com/science/article/pii/S2001037022001738), which does not include some of the more recent methods but does discuss CHP.
    - [ ] Can we estimate CHP in trans-QTLs by looking at the effect of the same variant across all tested molecular traits?
    - [ ] Existing methods for handling CHP do not seem to use empirical Bayes methods - can we use SuSiE to help us do this?
    - [ ] How can we have an infinitesimal model that also handles CHP?  No existing approach seems to be able to handle this.
## Colocalization
- [ ] "Infinitesimal model" of colocalization (this will definitely be a separate manuscript) - can we treat gene-level colocalization as a Kullbeik-Leibler divergence between two multivariate normal distributions?  Can we penalize this divergence for LD using the entropy of the distribution of the (top or all?) eigenvalues of the LD matrix?
## Polygenic molecular risk scores (PMRS)
- [ ] SuSiE model is ready made for prediction of molecular trait - make it easy to do predictions from new genotype data
- [ ] Genome-wide prediction will have the same concerns about CHP - this doesn't matter for predicting traits from PMRS, but does matter for model interpretation
- [ ] Use SuSiE to predict traits from PMRS - similar idea to CTWAS, definitely a separate manuscript, would want to extend to survival models.
## Interfaces with other packages
- [ ] `mvsusier`/`mvsusiF`
   - [ ] Straight forward for integrating with TWAS and MR - we use just the posterior effect size estimates as we normally do
   - [ ] Challenging for colocalization - `colocBoost` is the current solution, hopefully we can figure something out here later
- [ ] `susiF`
- [ ] vignette for INTACT
- [ ] vignette for CTWAS - currently challenging to run CTWAS
## Other
- [ ] Easy approach to adjust fine mapping to remove variants that were not tested in the GWAS but were tested in the QTL
- [ ] Vignette on imputing GWAS summary statistics (and QTL summary statistics if not using individual level QTL data) - this would ideally be tied to future efforts to improve this approach methodologically.

**Comment by gaow** [comment]
> ￼ mr.ash priors￼

I think we now have the `...` approach to accept arbitrary input parameters for individual methods. So what we need would be vignettes to show the use of various flavors of methods. As of today the only TWAS vignette we have is mr.mash 

> ￼ vignette for CTWAS - currently challenging to run CTWAS

As of now the `main` branch for cTWAS is broken. I've talked to people in Xin's group -- it should be possible to involve them in the xQTL project focused on delivering this part. I'll talk to Xin more formally in the following couple of weeks.

**Comment by gaow** [comment]
Updates on the original post

1. cTWAS -- my team is working actively with Xin's to refactor the package but still WIP
2. mr_ash_rss Rcpp is roughly done: we still need to compare it against the individual level, add additional parameters to be consistent with that, and also add some `omp` on the loops to parallel, just like what we do for other Rcpp applications under `src`
3. prs_cs Rcpp is roughly done. It is hard to compare numerically with the original implementation (MCMC by nature) but we should need another pair of eyes to read compare manually line by line if we did the right thing. I have done that myself I think it seems fine.

**Comment by danielnachun** [comment]
~~I recently reread the SuSiE-inf paper (https://pubmed.ncbi.nlm.nih.gov/38036779/) and now understand that this model is really just extending SuSiE to do variance components estimation to handle stratification instead of residualizing ancestry PCs.  I have some ideas on how to do this in a way that is more suitable for QTLs and could be treated as a 'pre-processing' step rather than having to modify how SuSiE itself runs.  This approach could also be make to work with `mr.ash` or other penalized regression methods.  Importantly, nothing in `pecotmr` would need to be modified for any of this to work, including the original implementation of SuSiE-inf.  Consequently I've cleaned up and corrected various mistakes in my original post to incorporate this knowledge along with some other topics as well.~~  The explanation here was slightly incorrect but we have SuSiE-inf now in SuSiER so this has been addressed in a different way.
